import operator
from pydantic import BaseModel
from typing import Annotated, Optional
from langgraph.graph import add_messages

class ResearcherState(BaseModel):
    """The state of the researcher agent. 
    
    The research_reports attribute is shared with the supervisor state. This allows the supervisor to access the research reports generated by the researcher and share them with the copywriter.
    """
    messages: Annotated[list, add_messages] = []
    
    query: Optional[str] = None
    
    retrieved_docs: Annotated[list, operator.add] = None
    
    web_results: Annotated[list, operator.add] = None
    
    final_answer: Optional[str] = None

    need_web_search: bool = False

    error: Optional[str] = None