import operator
from dotenv import load_dotenv
from pydantic import BaseModel
from typing import Annotated, Literal
from langchain_core.messages import SystemMessage, ToolMessage, HumanMessage, AIMessage, AIMessageChunk
from langgraph.graph import StateGraph, add_messages, END
from langgraph.prebuilt import ToolNode
from langchain_core.tools import tool, InjectedToolCallId
from langgraph.checkpoint.memory import MemorySaver
from datetime import datetime
from langgraph.types import Command, RunnableConfig
from langchain_ollama.chat_models import ChatOllama
from src.multi_agent.researcher.researcher import graph as research_agent
from src.multi_agent.copywriter.copywriter import graph as copywriter_agent


from rich.console import Console
from rich.panel import Panel

load_dotenv()

# Load the supervisor system prompt
supervisor_prompt = open("src/prompts/supervisor.md", "r").read()


class SupervisorState(BaseModel):
    """The state of the supervisor agent. 
    
    The research_reports attribute is shared with the researcher agent. This allows us to share the research reports between the researcher and copywriter agents.
    """
    messages: Annotated[list, add_messages] = []
    research_reports: Annotated[list, operator.add] = []
    task_description: str | None = None


@tool
async def handoff_to_subagent(
    agent_name: Literal["researcher", "copywriter"],
    task_description: str,
    tool_call_id: Annotated[str, InjectedToolCallId],
    ):
    """Assign a task to a sub-agent: researcher or copywriter.
    
    Args:
        agent_name: The name of the agent to handoff the task to. Valid agent names are researcher and copywriter.
        task_description: The description of the task to be completed.
    """
    # Construct the update schema for the Command primitive
    # We're specifying to update the task description in the state and add a tool message to the conversation to let the supervisor know the task has been handed off.
    update = {
        "task_description": task_description,
        "messages": [ToolMessage(
            name=f"handoff_to_{agent_name}",
            content=f"Successfully handed off task to {agent_name}.",
            tool_call_id=tool_call_id,
        )],
        }

    # Return the Command primitive with the update to the state and specifying the next node to go to
    return Command(
        goto=f"call_{agent_name}",
        update=update
        )


async def call_researcher(state: SupervisorState, config: RunnableConfig):
    """Call the researcher agent.
    
    The agent is invoked only with the task description generated by the supervisor, so the context window is not cluttered with the full conversation history of the supervisor.
    """
    research_response = await research_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            },
        config=config,
    )

    ai_message = AIMessage(name="researcher", content=research_response["messages"][-1].content)

    return {
        "research_reports": research_response["research_reports"],
        "messages": [ai_message],
        }

async def call_copywriter(state: SupervisorState, config: RunnableConfig):
    """Call the copywriter agent.
    
    The agent is invoked only with the task description generated by the supervisor, and any research reports that have been generated by the researcher.
    """
    copywriter_response = await copywriter_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            "research_reports": state.research_reports,
            },
        config=config,
        )
    
    ai_message = AIMessage(name="copywriter", content=copywriter_response["messages"][-1].content)

    return {"messages": [ai_message]}

llm = ChatOllama(
    model="llama3.2:3b",
    temperature=0,
)

tools=[handoff_to_subagent]
llm_with_tools = llm.bind_tools(tools)


async def supervisor(state: SupervisorState):
    """The main supervisor agent."""

    print("\n--- SUPERVISOR STATE MESSAGES ---")
    for msg in state.messages:
        print(msg)
    print("--------------------------------\n")

    response = llm_with_tools.invoke([
        SystemMessage(content=supervisor_prompt.format(current_datetime=datetime.now()))
        ] + state.messages)
    return {"messages": [response]}

async def supervisor_router(state: SupervisorState) -> str:
    """Route to the tools node if the supervisor makes a tool call."""
    if state.messages[-1].tool_calls:
        return "tools"
    return END

builder = StateGraph(SupervisorState)

builder.add_node(
    supervisor, 
    # This is a new feature and is only needed for visualization, doesn't impact runtime
    # destinations=("tools", "call_researcher", "call_copywriter", END)
    )
builder.add_node("tools", ToolNode(tools))
builder.add_node(call_researcher)
builder.add_node(call_copywriter)

builder.set_entry_point("supervisor")

builder.add_conditional_edges(
    "supervisor",
    supervisor_router,
    {
        "tools": "tools",
        END: END,
    }
)
# Normally we route back to the agent after a tool call. In this case we're using the Command primitive in the tool call to do the routing. So we don't need this typical edge.
# builder.add_edge("tools", "supervisor")

# Now every time we call a sub-agent we need to route back to the supervisor
builder.add_edge("call_researcher", "supervisor")
builder.add_edge("call_copywriter", "supervisor")

graph = builder.compile(checkpointer=MemorySaver())


# Visualize the graph
# from IPython.display import Image
# Image(graph.get_graph(xray=True).draw_mermaid_png())


# import asyncio
# from langchain_core.messages import HumanMessage, AIMessageChunk

# class StreamProcessor:
#     async def process(self, graph, input, config):
#         async for chunk, metadata in graph.astream(
#             input=input,
#             stream_mode="messages",
#             config=config
#         ):
#             if not isinstance(chunk, AIMessageChunk):
#                 continue

#             if chunk.response_metadata:
#                 if chunk.response_metadata.get("finish_reason") == "tool_calls":
#                     yield "\n\n"

#             if chunk.tool_call_chunks:
#                 for tool in chunk.tool_call_chunks:
#                     tool_name = tool.get("name", "")
#                     args = tool.get("args", "")

#                     if tool_name:
#                         yield f"\n\n< TOOL CALL: {tool_name} >\n\n"
#                     if args:
#                         yield args
#             else:
#                 yield chunk.content or ""

# async def main():
#     streamer = StreamProcessor()

#     graph_config = {
#         "configurable": {
#             "thread_id": "1"
#         }
#     }

#     while True:
#         user_input = input("\n\nUSER: ")
#         if user_input in ["quit", "exit"]:
#             break

#         print("\n ----  ASSISTANT  ---- \n\n")

#         async for chunk in streamer.process(
#             graph=graph,
#             input=SupervisorState(
#                 messages=[HumanMessage(content=user_input)]
#             ),
#             config=graph_config,
#         ):
#             print(chunk, end="", flush=True)


# if __name__ == "__main__":
#     asyncio.run(main())


def get_responsive_width(console: Console) -> int:
    """Get responsive width with margins for panels."""
    return min(120, console.size.width - 4) if console.size.width > 10 else 80

async def stream_graph_responses(
        input: SupervisorState,
        graph: StateGraph,
        console: Console,
        **kwargs
        ):
    """Asynchronously stream the result of the graph run with subgraph support.

    Args:
        input: The input to the graph.
        graph: The compiled graph.
        console: Rich console for output.
        **kwargs: Additional keyword arguments.

    Returns:
        str: The final LLM or tool call response
    """
    # Agent styling configuration
    AGENT_STYLES = {
        'researcher': {'color': 'cyan', 'emoji': '🔬', 'name': 'Researcher'},
        'copywriter': {'color': 'magenta', 'emoji': '✍️', 'name': 'Copywriter'},
        'supervisor': {'color': 'green', 'emoji': '🎯', 'name': 'Supervisor'},
    }

    # Track current AI message source to detect transitions
    current_ai_source = None
    current_content = ""
    current_tool_args = ""
    current_tool_name = ""

    async for chunk in graph.astream(
        input=input,
        stream_mode="messages",
        subgraphs=True,
        **kwargs
        ):
        # When subgraphs=True, the structure is (namespace, (message_chunk, metadata))
        namespace, (message_chunk, _) = chunk

        if isinstance(message_chunk, AIMessageChunk):
            # Determine the source of this AI message directly from namespace
            if namespace:
                # This is from a subgraph - detect agent from namespace
                namespace_str = str(namespace)
                if "call_researcher" in namespace_str:
                    ai_source = "researcher"
                elif "call_copywriter" in namespace_str:
                    ai_source = "copywriter"
                else:
                    # Fallback for unknown subgraphs
                    ai_source = "researcher"
            else:
                # This is from the main graph (supervisor)
                ai_source = "supervisor"

            # Check if we're transitioning between different AI sources
            if current_ai_source != ai_source:
                # Finalize previous agent's content in a panel
                if current_content.strip() and current_ai_source:
                    style = AGENT_STYLES[current_ai_source]
                    panel = Panel(
                        current_content.strip(),
                        title=f"{style['emoji']} {style['name']}",
                        border_style=style['color'],
                        title_align="left",
                        padding=(1, 2),
                        width=get_responsive_width(console)
                    )
                    console.print(panel)
                    console.print()  # Add spacing after completed panel

                # Start new agent
                current_ai_source = ai_source
                current_content = ""
            elif current_ai_source is None:
                # First AI message
                current_ai_source = ai_source
                current_content = ""

            # Handle tool calls
            if message_chunk.response_metadata:
                finish_reason = message_chunk.response_metadata.get("finish_reason", "")
                if finish_reason == "tool_calls":
                    # Print accumulated tool args if we have them
                    if current_tool_args.strip():
                        if current_ai_source:
                            style = AGENT_STYLES[current_ai_source]
                            console.print(f"  [dim {style['color']}]{current_tool_args.strip()}[/dim {style['color']}]")
                        else:
                            console.print(f"  [dim]{current_tool_args.strip()}[/dim]")
                        current_tool_args = ""
                    console.print("  🔧 [yellow]Tool call completed[/yellow]")
                    console.print()  # Add spacing after tool completion

            if message_chunk.tool_call_chunks:
                tool_chunk = message_chunk.tool_call_chunks[0]
                tool_name = tool_chunk.get("name", "")
                args = tool_chunk.get("args", "")

                if tool_name and tool_name != current_tool_name:
                    # New tool call - print the name
                    console.print(f"  🔧 [yellow]TOOL CALL: {tool_name}[/yellow]")
                    current_tool_name = tool_name
                    current_tool_args = ""  # Reset args for new tool

                if args:
                    # Accumulate args instead of printing immediately
                    current_tool_args += args
            else:
                # Just accumulate content for panel display
                if message_chunk.content:
                    current_content += message_chunk.content
        else:
            # Handle other message types
            pass

    # Print any remaining tool args
    if current_tool_args.strip():
        if current_ai_source:
            style = AGENT_STYLES[current_ai_source]
            console.print(f"  [dim {style['color']}]{current_tool_args.strip()}[/dim {style['color']}]")
        else:
            console.print(f"  [dim]{current_tool_args.strip()}[/dim]")
        console.print()

    # Finalize the last agent's content in a panel
    if current_content.strip() and current_ai_source:
        style = AGENT_STYLES[current_ai_source]
        panel = Panel(
            current_content.strip(),
            title=f"{style['emoji']} {style['name']}",
            border_style=style['color'],
            title_align="left",
            padding=(1, 2),
            width=get_responsive_width(console)
        )
        console.print(panel)
        console.print()  # Add spacing after final panel


async def main():
    """Main function to run the supervisor with subgraphs."""
    # Create console without fixed width - let it be responsive
    console = Console()

    try:
        config = RunnableConfig(configurable={
            "thread_id": "1",
            "recursion_limit": 50,
        })

        # Welcome panel with responsive width
        welcome_panel = Panel(
            "Multi-Agent Supervisor with Subgraphs\nType 'exit' or 'quit' to stop",
            title="🚀 AI Launchpad",
            border_style="blue",
            title_align="center",
            padding=(1, 2),  # Add padding to welcome panel
            width=get_responsive_width(console)
        )
        console.print(welcome_panel)
        console.print()  # Add spacing after welcome

        while True:
            console.print()
            user_input = console.input("[bold blue]User:[/bold blue] ")
            console.print()  # Add spacing after user input

            if user_input.lower() in ["exit", "quit"]:
                console.print("\n[yellow]Exit command received. Goodbye! 👋[/yellow]\n")
                break

            graph_input = SupervisorState(
                messages=[HumanMessage(content=user_input)]
            )

            await stream_graph_responses(graph_input, graph, console, config=config)

    except Exception as e:
        console.print(f"[red]Error: {type(e).__name__}: {str(e)}[/red]")
        raise

    
# Example prompts
# write a linkedin post on the top AI tools that small businesses and entrepreneurs need to be using to scale their businesses. include real-world examples and case studies where businesses are using these tools to scale their business with real numbers. include a call to action at the end for readers to follow me for more actionable playbooks on how to generate real value for their business.