from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver
from datetime import datetime
from dotenv import load_dotenv
from langgraph.types import RunnableConfig
from src.multi_agent.researcher.graph import ResearcherAgent
from src.multi_agent.supervisor.state import SupervisorState
from src.multi_agent.supervisor.tools import handoff_to_subagent
from src.prompts.prompt_manager import PromptManager
from src.utils.llm_factory import LLMFactory, ModelTier

load_dotenv()

class SupervisorAgent:
    def __init__(self):
        self.graph = None
        self.tools = None
        self._prompt_manager = PromptManager()
        
        self.tools = [handoff_to_subagent]

        tools_context = "\n".join(
            f"{tool.name}: {tool.description}"
            for tool in self.tools
        )

        self.supervisor_prompt = self._prompt_manager.get("supervisor", tools=tools_context, current_datetime=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        factory = LLMFactory.get_instance()
        self.llm_with_tools = factory.get_tool_llm(ModelTier.REMOTE, self.tools)

        self.research_agent = ResearcherAgent()

    async def build_graph(self):
        """Kreira LangGraph."""
        builder = StateGraph(SupervisorState)

        self.research_graph = await self.research_agent.initialize()

        builder.add_node(self.supervisor)
        builder.add_node("tools", ToolNode(self.tools))
        builder.add_node(self.call_researcher)

        builder.set_entry_point("supervisor")

        builder.add_conditional_edges(
            "supervisor",
            self.supervisor_router,
            {
                "tools": "tools",
                END: END,
            }
        )

        builder.add_edge("call_researcher", "supervisor")

        self.graph = builder.compile(checkpointer=MemorySaver())

        return self.graph
    
    async def supervisor(self, state: SupervisorState):
        """The main supervisor agent."""

        # Build messages
        messages = [SystemMessage(content = self.supervisor_prompt)]

        response = await self.llm_with_tools.ainvoke(messages + state.messages)

        print("\n--- SUPERVISOR STATE ---")
        print(type(response).__name__, getattr(response, "content", ""))
        if hasattr(response, "tool_calls"):
            print("TOOL CALLS:", response.tool_calls)

        return {"messages": [response]}

    async def supervisor_router(self, state: SupervisorState) -> str:
        """Route to the tools node if the supervisor makes a tool call."""
        last_message = state.messages[-1]

        if isinstance(last_message, AIMessage) and last_message.name == "researcher":
            return END

        if last_message.tool_calls:
            return "tools"
        return END
    
    async def call_researcher(self, state: SupervisorState, config: RunnableConfig):
        """Call the researcher agent.
        
        The agent is invoked with the task description generated by the supervisor, and any research reports that have been generated by the researcher.
        """
        research_response = await self.research_graph.ainvoke(
            input={
                "messages": [HumanMessage(content=state.task_description)],
                "query": state.task_description,
                },
            config=config,
        )

        print("\n--- RESEARCHER STATE ---\n")
        print(type(research_response).__name__, getattr(research_response["messages"][-1], "content", ""))
        if hasattr(research_response["messages"][-1], "tool_calls"):
            print("TOOL CALLS:", research_response["messages"][-1].tool_calls)

        ai_message = AIMessage(
            name="researcher", 
            content=research_response['messages'][-1].content
        )

        return {
            "messages": [ai_message],
        }

# Visualize the graph
# from IPython.display import Image
# Image(graph.get_graph().draw_mermaid_png())