from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver
from datetime import datetime
from dotenv import load_dotenv
from langgraph.types import RunnableConfig
from langchain_ollama.chat_models import ChatOllama
from src.multi_agent.researcher.graph import graph as research_agent
from src.multi_agent.copywriter.graph import graph as copywriter_agent
from src.multi_agent.supervisor.state import SupervisorState
from src.multi_agent.supervisor.tools import handoff_to_subagent

load_dotenv()

async def call_researcher(state: SupervisorState, config: RunnableConfig):
    """Call the researcher agent.
    
    The agent is invoked only with the task description generated by the supervisor, so the context window is not cluttered with the full conversation history of the supervisor.
    """
    research_response = await research_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            },
        config=config,
    )

    ai_message = AIMessage(name="researcher", content=research_response["messages"][-1].content)

    return {
        "research_reports": research_response["research_reports"],
        "messages": [ai_message],
    }

async def call_copywriter(state: SupervisorState, config: RunnableConfig):
    """Call the copywriter agent.
    
    The agent is invoked only with the task description generated by the supervisor, and any research reports that have been generated by the researcher.
    """
    copywriter_response = await copywriter_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            "research_reports": state.research_reports,
            },
        config=config,
        )
    
    ai_message = AIMessage(name="copywriter", content=copywriter_response["messages"][-1].content)

    return {"messages": [ai_message]}

llm = ChatOllama(
    model="llama3.2:3b",
    temperature=0,
)

tools = [handoff_to_subagent]
llm_with_tools = llm.bind_tools(tools)

# Load the supervisor system prompt
supervisor_prompt = open("src/prompts/supervisor.md", "r").read()

async def supervisor(state: SupervisorState):
    """The main supervisor agent."""

    print("\n--- SUPERVISOR STATE MESSAGES ---")
    for msg in state.messages:
        print(msg)
    print("--------------------------------\n")

    response = llm_with_tools.invoke([
        SystemMessage(content = supervisor_prompt.format(current_datetime=datetime.now()))
        ] + state.messages)
    return {"messages": [response]}

async def supervisor_router(state: SupervisorState) -> str:
    """Route to the tools node if the supervisor makes a tool call."""
    if state.messages[-1].tool_calls:
        return "tools"
    return END

builder = StateGraph(SupervisorState)

builder.add_node(
    supervisor, 
    # This is a new feature and is only needed for visualization, doesn't impact runtime
    # destinations=("tools", "call_researcher", "call_copywriter", END)
    )
builder.add_node("tools", ToolNode(tools))
builder.add_node(call_researcher)
builder.add_node(call_copywriter)

builder.set_entry_point("supervisor")

builder.add_conditional_edges(
    "supervisor",
    supervisor_router,
    {
        "tools": "tools",
        END: END,
    }
)
# Normally we route back to the agent after a tool call. In this case we're using the Command primitive in the tool call to do the routing. So we don't need this typical edge.
# builder.add_edge("tools", "supervisor")

# Now every time we call a sub-agent we need to route back to the supervisor
builder.add_edge("call_researcher", "supervisor")
builder.add_edge("call_copywriter", "supervisor")

graph = builder.compile(checkpointer=MemorySaver())
